const FETCH_REQUEST = 'FETCH_REQUEST';
const FETCH_SUCCESS = 'FETCH_SUCCESS';
const FETCH_FAILURE = 'FETCH_FAILURE';
const CHANGE_FILTER = 'CHANGE_FILTER';
const CHANGE_CAMERAS = 'CHANGE_CAMERAS';
const CHANGE_PHOTO = 'CHANGE_PHOTO';
const CHANGE_VISITED = 'CHANGE_VISITED';

export {
    FETCH_REQUEST,
    FETCH_SUCCESS,
    FETCH_FAILURE,
    CHANGE_FILTER,
    CHANGE_CAMERAS,
    CHANGE_PHOTO,
    CHANGE_VISITED
}